apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mern-frontend
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
