import { Typography } from '@mui/material';
import { Box } from '@mui/system';
import React from 'react';
import Block from '../global/Block';
import CodeBox from '../global/CodeBox';
import ImageComp from '../EnvironmentSetup/ImageComp';
import Process from '../EnvironmentSetup/Process';

const list = [
    ".next/: This folder is created when we run the dev or the build scripts. Our Next.js application is served from this foler.",
    "node_modules/: This is where the dependencies installed via npm or yarn are stored.",
    "pages/: This directory contains individual files that represent different routes or pages in our application.",
    "api/: This is the folder where we create APIs for our application.",
    "_app.js: This is the file where we define the layout of our application.",
    "index.js: This file represents the homepage or landing page of your application.",
    "public/: This folder is used to store static files that will be served directly to the client.",
    "styles/: This folder contains your application's CSS or styling files.",
    ".estlint.rc: This is the configuration file for the estlint.",
    ".gitignore: This file specifies the files and directories that should be ignored by Git version control.",
    "next.config.js/: This is the Next.js configuration file.",
    "package.json: This file contains the project configuration, scripts, and dependencies for your Next.js app.",
    "README.md: This file typically contains documentation and instructions for setting up and running the project.",
    "package-lock.json: This file is generated by npm/yarn and locks the exact versions of the installed dependencies."

];


const NextProjectStructure = () => {
    return (
        <Box pb={3}>
            <Typography variant='h3'>Project Structure of a NextJS application</Typography>
            <Typography variant='subtitle2'>
                When creating a Next.js app, the project structure may vary depending on your preferences and requirements. However, this is what a typical Next.js project structure may look like when created using npm:
            </Typography>

            <ImageComp image={"/nextjs/Screenshot_structure.png"} imageTitle={"Screenshot 1: Project structure"}></ImageComp>

            <Box mt={3}>
                <Process list={list}></Process>
            </Box>


            <Typography mt={2} variant='subtitle2'>
                It should be noted that this is the default project structure of a simple Next.js app. You can customize the structure according to your preference as you start developing your application.
            </Typography>


        </Box>
    );
};

export default NextProjectStructure;